import { Job } from '../src/models/index.js'

const jharkhandJobs = [
  {
    id: 'jssc-cgl-2026',
    title: 'JSSC CGL Recruitment 2026 (JGGLCCE) — 2,025 Posts',
    org: 'Jharkhand Staff Selection Commission',
    orgShort: 'JSSC',
    category: 'jssc',
    kind: 'job',
    tagline: 'Jharkhand General Graduate Level Combined Competitive Exam 2026',
    shortInfo: 'Jharkhand Staff Selection Commission (JSSC) invites online applications for 2,025 Assistant Branch Officer, Block Supply Officer, Planning Assistant, and Junior Secretariat Assistant posts.',
    detailedDescription: '<h3>JSSC CGL Recruitment 2026 Notification</h3><p>Jharkhand Staff Selection Commission (JSSC) has released the official notification for Jharkhand General Graduate Level Combined Competitive Exam (JGGLCCE 2026). Eligible candidates possessing a Bachelor degree from a recognized university can apply online.</p>',
    applyUrl: 'https://jssc.jharkhand.gov.in',
    notificationPdfUrl: 'https://jssc.jharkhand.gov.in/notices',
    officialWebsiteUrl: 'https://jssc.jharkhand.gov.in',
    eligibility: 'Bachelor Degree in any stream from a recognized University in India.',
    eligibilityShort: 'Graduate Pass',
    postedAt: 'Online Form',
    postedOn: '10-09-2026',
    vacancies: 2025,
    featured: true,
    inTicker: true,
    logo: { icon: 'scale', color: '#09324A' },
    importantDates: [
      { label: 'Application Begin', value: '15-09-2026' },
      { label: 'Last Date to Apply', value: '15-10-2026' },
      { label: 'Exam Date', value: 'November 2026' },
    ],
    fee: [
      { label: 'UR / EWS / EBC / BC', value: '₹100' },
      { label: 'SC / ST of Jharkhand', value: '₹50' },
    ],
    ageLimit: { min: 21, max: 35, note: 'Age relaxation as per Jharkhand Govt rules.' },
    posts: [
      { name: 'Assistant Branch Officer', total: '863', eligibility: 'Bachelor Degree' },
      { name: 'Junior Secretariat Assistant', total: '335', eligibility: 'Bachelor Degree' },
      { name: 'Block Supply Officer', total: '252', eligibility: 'Bachelor Degree' },
      { name: 'Planning Assistant', total: '5', eligibility: 'Bachelor Degree' },
    ],
    links: [
      { label: 'Apply Online', href: 'https://jssc.jharkhand.gov.in', primary: true },
      { label: 'Official Notification', href: 'https://jssc.jharkhand.gov.in', primary: false },
      { label: 'Official Website', href: 'https://jssc.jharkhand.gov.in', primary: false },
    ],
  },
  {
    id: 'jssc-jcce-constable-2026',
    title: 'Jharkhand Police Constable Recruitment 2026 (JCCE) — 4,919 Posts',
    org: 'Jharkhand Staff Selection Commission',
    orgShort: 'JSSC',
    category: 'jssc',
    kind: 'job',
    tagline: 'Jharkhand Constable Competitive Examination 2026',
    shortInfo: 'JSSC invites online applications for 4,919 Police Constable vacancies across district police forces in Jharkhand.',
    detailedDescription: '<h3>Jharkhand Police Constable (JCCE) 2026</h3><p>Online applications are invited from 10th pass candidates for recruitment to Jharkhand Police Constable vacancies across all 24 districts.</p>',
    applyUrl: 'https://jssc.jharkhand.gov.in',
    notificationPdfUrl: 'https://jssc.jharkhand.gov.in',
    officialWebsiteUrl: 'https://jssc.jharkhand.gov.in',
    eligibility: '10th (Matriculation) Pass from recognized Board.',
    eligibilityShort: '10th Pass',
    postedAt: 'Online Form',
    postedOn: '08-09-2026',
    vacancies: 4919,
    featured: true,
    inTicker: true,
    logo: { icon: 'siren', color: '#09324A' },
    importantDates: [
      { label: 'Application Begin', value: '20-09-2026' },
      { label: 'Last Date to Apply', value: '20-10-2026' },
      { label: 'Physical Test (PET)', value: 'December 2026' },
    ],
    fee: [
      { label: 'General / OBC / EWS', value: '₹100' },
      { label: 'SC / ST of Jharkhand', value: '₹50' },
    ],
    ageLimit: { min: 18, max: 25, note: 'Relaxation for Jharkhand OBC/SC/ST as per norms.' },
    posts: [
      { name: 'District Police Constable (Regular)', total: '3799', eligibility: '10th Pass' },
      { name: 'District Police Constable (Backlog)', total: '1120', eligibility: '10th Pass' },
    ],
    links: [
      { label: 'Apply Online', href: 'https://jssc.jharkhand.gov.in', primary: true },
      { label: 'Official Website', href: 'https://jssc.jharkhand.gov.in', primary: false },
    ],
  },
  {
    id: 'jpsc-civil-services-2026',
    title: 'JPSC Combined Civil Services Examination 2026 — 342 Posts',
    org: 'Jharkhand Public Service Commission',
    orgShort: 'JPSC',
    category: 'jpsc',
    kind: 'job',
    tagline: 'Jharkhand Administrative & Police Service 2026',
    shortInfo: 'Jharkhand Public Service Commission (JPSC) invites online applications for Jharkhand Administrative Service, Jharkhand Police Service, and allied state services.',
    detailedDescription: '<h3>JPSC Combined Civil Services 2026</h3><p>Official notification for JPSC Combined Civil Services Examination 2026 for recruitment to state civil administrative cadre.</p>',
    applyUrl: 'https://jpsc.gov.in',
    notificationPdfUrl: 'https://jpsc.gov.in',
    officialWebsiteUrl: 'https://jpsc.gov.in',
    eligibility: 'Bachelor Degree in any discipline from a recognized University.',
    eligibilityShort: 'Any Degree',
    postedAt: 'Notification Out',
    postedOn: '11-09-2026',
    vacancies: 342,
    featured: true,
    inTicker: true,
    logo: { icon: 'landmark', color: '#1B6F81' },
    importantDates: [
      { label: 'Application Begin', value: '18-09-2026' },
      { label: 'Last Date to Apply', value: '18-10-2026' },
      { label: 'Prelims Exam Date', value: 'December 2026' },
    ],
    fee: [
      { label: 'UR / EWS / BC / EBC', value: '₹100' },
      { label: 'SC / ST of Jharkhand', value: '₹50' },
    ],
    ageLimit: { min: 21, max: 35, note: 'Age relaxation applicable for Jharkhand residents.' },
    posts: [
      { name: 'Jharkhand Administrative Service (Dy. Collector)', total: '207', eligibility: 'Graduate' },
      { name: 'Jharkhand Police Service (DSP)', total: '35', eligibility: 'Graduate' },
      { name: 'Jharkhand Prison Service', total: '18', eligibility: 'Graduate' },
      { name: 'Jharkhand Probation Service', total: '82', eligibility: 'Graduate' },
    ],
    links: [
      { label: 'Apply Online', href: 'https://jpsc.gov.in', primary: true },
      { label: 'Official Website', href: 'https://jpsc.gov.in', primary: false },
    ],
  },
  {
    id: 'jpsc-cdpo-recruitment-2026',
    title: 'JPSC CDPO Recruitment 2026 — 64 Posts',
    org: 'Jharkhand Public Service Commission',
    orgShort: 'JPSC',
    category: 'jpsc',
    kind: 'job',
    tagline: 'Child Development Project Officer (CDPO) Examination',
    shortInfo: 'JPSC invites applications for Child Development Project Officer in the Women and Child Development Department of Jharkhand.',
    detailedDescription: '<h3>JPSC CDPO Vacancy 2026</h3><p>Applications are open for Child Development Project Officer (CDPO) posts under Jharkhand WCD department.</p>',
    applyUrl: 'https://jpsc.gov.in',
    notificationPdfUrl: 'https://jpsc.gov.in',
    officialWebsiteUrl: 'https://jpsc.gov.in',
    eligibility: 'Graduate degree from any recognized university.',
    eligibilityShort: 'Graduate',
    postedAt: 'Apply Online',
    postedOn: '05-09-2026',
    vacancies: 64,
    featured: false,
    inTicker: false,
    logo: { icon: 'landmark', color: '#1B6F81' },
    importantDates: [
      { label: 'Application Begin', value: '01-09-2026' },
      { label: 'Last Date to Apply', value: '30-09-2026' },
    ],
    fee: [
      { label: 'UR / OBC / EWS', value: '₹600' },
      { label: 'SC / ST of Jharkhand', value: '₹150' },
    ],
    ageLimit: { min: 22, max: 35, note: 'Age relaxation as per state government rules.' },
    posts: [{ name: 'Child Development Project Officer', total: '64', eligibility: 'Graduate' }],
    links: [{ label: 'Apply Online', href: 'https://jpsc.gov.in', primary: true }],
  },
  {
    id: 'jharkhand-rojgar-mela-ranchi-2026',
    title: 'Jharkhand Rojgar Mela Ranchi District Bharti Camp 2026 — 1,500 Vacancies',
    org: 'Department of Labour, Employment & Training Jharkhand',
    orgShort: 'Rojgar Mela',
    category: 'rojgar-mela',
    kind: 'job',
    tagline: 'District Recruitment Camp & Spot Placement Fair',
    shortInfo: 'Direct recruitment drive & spot interviews conducted by District Employment Exchange Ranchi for 10th, 12th, ITI, Diploma, and Graduate candidates.',
    detailedDescription: '<h3>Jharkhand Rojgar Mela 2026 — Ranchi</h3><p>Rojgar Bharti Camp will be organized at District Employment Exchange, ITI Campus, Ranchi. Multiple private employers offering on-the-spot offer letters.</p>',
    applyUrl: 'https://rojgar.jharkhand.gov.in',
    notificationPdfUrl: 'https://rojgar.jharkhand.gov.in',
    officialWebsiteUrl: 'https://rojgar.jharkhand.gov.in',
    eligibility: '8th / 10th / 12th / ITI / Diploma / Any Graduate.',
    eligibilityShort: '8th to Graduate',
    postedAt: 'Spot Hiring',
    postedOn: '12-09-2026',
    vacancies: 1500,
    featured: true,
    inTicker: true,
    logo: { icon: 'users', color: '#b45309' },
    importantDates: [
      { label: 'Registration Open', value: '10-09-2026' },
      { label: 'Camp / Interview Date', value: '25-09-2026' },
    ],
    fee: [
      { label: 'All Candidates', value: '₹0 (Free Registration)' },
    ],
    ageLimit: { min: 18, max: 40, note: 'Valid Jharkhand Employment Exchange registration required.' },
    posts: [
      { name: 'Technician / Trainee', total: '650', eligibility: '10th / ITI' },
      { name: 'Sales Executive / Field Officer', total: '450', eligibility: '12th / Any Degree' },
      { name: 'Office Assistant / Data Entry', total: '400', eligibility: '12th / Computer' },
    ],
    links: [
      { label: 'Register on Rojgar Portal', href: 'https://rojgar.jharkhand.gov.in', primary: true },
      { label: 'Official Notice', href: 'https://rojgar.jharkhand.gov.in', primary: false },
    ],
  },
  {
    id: 'jharkhand-rojgar-mela-dhanbad-2026',
    title: 'Jharkhand Rojgar Mela Dhanbad Bharti Camp 2026 — 850 Vacancies',
    org: 'District Employment Exchange Dhanbad',
    orgShort: 'Rojgar Mela',
    category: 'rojgar-mela',
    kind: 'job',
    tagline: 'Dhanbad Employment Exchange Placement Drive',
    shortInfo: 'Sub-Regional Employment Exchange Dhanbad hosting Job Fair for various manufacturing, mining, and retail corporate openings.',
    detailedDescription: '<h3>Dhanbad Rojgar Mela 2026</h3><p>Jharkhand youth can attend the direct placement camp with resume, photos, and academic certificates.</p>',
    applyUrl: 'https://rojgar.jharkhand.gov.in',
    notificationPdfUrl: 'https://rojgar.jharkhand.gov.in',
    officialWebsiteUrl: 'https://rojgar.jharkhand.gov.in',
    eligibility: '10th / 12th / ITI / Graduate Pass.',
    eligibilityShort: '10th / ITI / Graduate',
    postedAt: 'Camp Live',
    postedOn: '09-09-2026',
    vacancies: 850,
    featured: false,
    inTicker: false,
    logo: { icon: 'users', color: '#b45309' },
    importantDates: [
      { label: 'Camp Date', value: '28-09-2026' },
      { label: 'Reporting Time', value: '10:00 AM' },
    ],
    fee: [{ label: 'Application Fee', value: '₹0 (Free)' }],
    ageLimit: { min: 18, max: 35, note: 'Open for all Jharkhand youth.' },
    posts: [{ name: 'Industrial Apprentice / Helper', total: '850', eligibility: '10th / ITI' }],
    links: [{ label: 'Official Portal', href: 'https://rojgar.jharkhand.gov.in', primary: true }],
  },
  {
    id: 'tata-steel-jamshedpur-apprentice-2026',
    title: 'Tata Steel Jamshedpur Trade Apprentice Recruitment 2026 — 600 Vacancies',
    org: 'Tata Steel Limited Jamshedpur',
    orgShort: 'Tata Steel',
    category: 'private',
    kind: 'job',
    tagline: 'Private Sector Industry Careers — Jamshedpur Plant',
    shortInfo: 'Tata Steel invites online applications from Jharkhand domicile candidates for Trade Apprentice training with assured stipend and plant absorption.',
    detailedDescription: '<h3>Tata Steel Jamshedpur Careers 2026</h3><p>Tata Steel Limited invites applications for 600 Trade Apprentice positions for their Jamshedpur operations.</p>',
    applyUrl: 'https://tatasteel.com/careers',
    notificationPdfUrl: 'https://tatasteel.com/careers',
    officialWebsiteUrl: 'https://tatasteel.com',
    eligibility: 'Matriculation or equivalent examination with 60% or more marks (50% for SC/ST).',
    eligibilityShort: '10th Pass (60%)',
    postedAt: 'Private Job',
    postedOn: '11-09-2026',
    vacancies: 600,
    featured: true,
    inTicker: true,
    logo: { icon: 'briefcase', color: '#0f766e' },
    importantDates: [
      { label: 'Application Begin', value: '12-09-2026' },
      { label: 'Last Date to Apply', value: '10-10-2026' },
      { label: 'Written Test', value: 'November 2026' },
    ],
    fee: [{ label: 'Assessment Fee', value: '₹350' }],
    ageLimit: { min: 18, max: 24, note: 'Jharkhand domicile candidates prioritized.' },
    posts: [{ name: 'Trade Apprentice (Mechanical / Electrical / Metallurgy)', total: '600', eligibility: '10th Pass' }],
    links: [
      { label: 'Apply on Tata Steel Careers', href: 'https://tatasteel.com/careers', primary: true },
      { label: 'Official Website', href: 'https://tatasteel.com', primary: false },
    ],
  },
  {
    id: 'jindal-steel-patratu-careers-2026',
    title: 'Jindal Steel & Power Patratu Plant Hiring 2026 — 250 Posts',
    org: 'Jindal Steel & Power Limited',
    orgShort: 'JSPL',
    category: 'private',
    kind: 'job',
    tagline: 'Private Industrial Engineering Vacancy — Ramgarh / Patratu',
    shortInfo: 'JSPL is recruiting Junior Engineers, Technicians, and Safety Officers for the Patratu Wire Rod Mill expansion in Ramgarh district.',
    detailedDescription: '<h3>Jindal Steel & Power Limited Recruitment</h3><p>Exciting private sector opportunities for engineers, diploma holders, and technicians at JSPL Patratu plant.</p>',
    applyUrl: 'https://jindalsteelpower.com/careers',
    notificationPdfUrl: 'https://jindalsteelpower.com',
    officialWebsiteUrl: 'https://jindalsteelpower.com',
    eligibility: 'Diploma / B.Tech / ITI in Mechanical / Electrical / Safety Engineering.',
    eligibilityShort: 'Diploma / B.Tech / ITI',
    postedAt: 'Private Job',
    postedOn: '10-09-2026',
    vacancies: 250,
    featured: false,
    inTicker: false,
    logo: { icon: 'briefcase', color: '#0f766e' },
    importantDates: [
      { label: 'Last Date to Apply', value: '15-10-2026' },
    ],
    fee: [{ label: 'Application Fee', value: '₹0 (Free)' }],
    ageLimit: { min: 21, max: 32, note: 'Freshers and experienced candidates eligible.' },
    posts: [{ name: 'Junior Engineer & Technician', total: '250', eligibility: 'Diploma / B.Tech' }],
    links: [{ label: 'Apply on JSPL Portal', href: 'https://jindalsteelpower.com/careers', primary: true }],
  },
]

async function seed() {
  try {
    for (const job of jharkhandJobs) {
      const existing = await Job.findByPk(job.id)
      if (existing) {
        await existing.update(job)
      } else {
        await Job.create(job)
      }
    }
    console.log('Jharkhand jobs seeded successfully! Total jobs:', jharkhandJobs.length)
  } catch (e) {
    console.error('Seeding error:', e)
  } finally {
    process.exit(0)
  }
}

seed()
